/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misPruebas;

// @author LENOVO

import java.awt.CardLayout;
import java.awt.Font;
import java.io.File;
import misClases.JPCreditos;
import misClases.JPInicio;
import misClases.JPInstrucciones;
import misClases.JPJuego;

public class JFAplicacion extends javax.swing.JFrame {
    // Variables
    private final CardLayout cardLayout;
    private final JPInicio card1;
    private final JPJuego card2;
    private final JPInstrucciones card3;
    private JPCreditos card6;
    
    // Fuentes Personalizadas
    private Font SVBold;
    private Font SVThin;
    
    // Creates new form FrameAplicacion
    public JFAplicacion() {
        loadFonts();
        initComponents();
        
        // Esto es para agregar los diferentes paneles en el JFrame principal
        cardLayout = (CardLayout)pantallaPrincipal.getLayout();
        
        pantallaPrincipal.setLayout(cardLayout);
        
        card1 = new JPInicio(SVBold,SVThin);
        card2 = new JPJuego(SVBold,SVThin);
        card3 = new JPInstrucciones(SVBold,SVThin);
        card6 = new JPCreditos(SVBold,SVThin);
        
        pantallaPrincipal.add(card1, "MainScreen");
        pantallaPrincipal.add(card2,"GameScreen");
        pantallaPrincipal.add(card3,"InstructScreen");
        pantallaPrincipal.add(card6,"CreditsScreen");
    }
    
    // Se encarga de cargar las fuentes de los recursos al JPanel tal cual
    private void loadFonts(){
        try{
            File fileSVBold = new File("src/Resources/Fuentes/svbold.otf");
            File fileSVThin = new File("src/Resources/Fuentes/svthin.otf");
            SVBold = Font.createFont(Font.TRUETYPE_FONT, fileSVBold).deriveFont(16f);
            SVThin = Font.createFont(Font.TRUETYPE_FONT, fileSVThin).deriveFont(16f);
            this.setFont(SVBold);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdivinaQuien");
        setName("AdivinaQuien"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        pantallaPrincipal.setMaximumSize(new java.awt.Dimension(1280, 720));
        pantallaPrincipal.setMinimumSize(new java.awt.Dimension(1280, 720));
        pantallaPrincipal.setPreferredSize(new java.awt.Dimension(1280, 720));
        pantallaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pantallaPrincipal;
    // End of variables declaration//GEN-END:variables
}
