/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package misClases;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

public class JDListaP extends javax.swing.JDialog {

    private ArrayList<Personaje> personajes = new ArrayList<>();
    private Personaje seleccionado;
    private Image imgFondo;
    
    public JDListaP(java.awt.Frame parent, ArrayList<Personaje> chara) {
        super(parent, true);
        try{
            imgFondo = ImageIO.read(new File("src/Resources/Fondos/Fondo3.png"));
        }catch(Exception e){
            System.out.println("*** Error cargando fondo de panel ***");
            e.printStackTrace();
        }
        initComponents();
        this.personajes = chara;
        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (int i = 0; i < personajes.size(); i++) {
            modelo.addElement(personajes.get(i).getNombre());
        }
        jListPersonajes.setModel(modelo);
        
        this.jPanelFondo.setOpaque(true);
        this.jPanelFondo.add(new JComponent(){
            @Override
            protected void paintComponent(Graphics g) {
                g.drawImage(imgFondo, 0, 0, jPanelFondo.getWidth(), jPanelFondo.getHeight(), this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPersonajes = new javax.swing.JList<>();
        jButtonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 304));
        setMinimumSize(new java.awt.Dimension(400, 304));

        jPanelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jPanelFondo.setMaximumSize(new java.awt.Dimension(400, 304));
        jPanelFondo.setMinimumSize(new java.awt.Dimension(400, 304));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(400, 304));

        jLabelTitulo.setFont(StardewFonts.getSVSmallTitle());
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Selecciona un Personaje:");

        jListPersonajes.setBackground(new java.awt.Color(255, 245, 202));
        jListPersonajes.setFont(StardewFonts.getSVThin());
        jListPersonajes.setMaximumSize(new java.awt.Dimension(250, 50));
        jScrollPane1.setViewportView(jListPersonajes);

        jButtonContinuar.setBackground(new java.awt.Color(218, 173, 114));
        jButtonContinuar.setFont(StardewFonts.getSVBold());
        jButtonContinuar.setText("Continuar");
        jButtonContinuar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(177, 78, 5)));
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        if(this.jListPersonajes.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un personaje");
        }
        else{
            seleccionado = personajes.get(this.jListPersonajes.getSelectedIndex());
            dispose();
        }
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    public Personaje getSeleccionado() {
        return seleccionado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListPersonajes;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
