/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.*;
import javax.swing.*;

// @author LENOVO

public class JPInicio extends javax.swing.JPanel {
    // Variables
    private Font SVBold;
    private Font SVThin;
    
    // Creates new form JPInicio
    public JPInicio(Font SVBold, Font SVThin) {
        this.SVBold = SVBold;
        this.SVThin = SVThin;
        this.setFont(SVThin);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonStart = new javax.swing.JButton();
        ButtonOption = new javax.swing.JButton();
        ButtonCredits = new javax.swing.JButton();

        setFont(getFont());
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        ButtonStart.setFont(SVBold);
        ButtonStart.setBorder(null);
        ButtonStart.setBorderPainted(false);
        ButtonStart.setLabel("Jugar");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        ButtonOption.setFont(getFont());
        ButtonOption.setText("Opciones");
        ButtonOption.setBorder(null);
        ButtonOption.setBorderPainted(false);
        ButtonOption.setIconTextGap(0);
        ButtonOption.setInheritsPopupMenu(true);
        ButtonOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOptionActionPerformed(evt);
            }
        });

        ButtonCredits.setFont(getFont());
        ButtonCredits.setText("Creditos");
        ButtonCredits.setBorder(null);
        ButtonCredits.setBorderPainted(false);
        ButtonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOption, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonOption, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        getAccessibleContext().setAccessibleName("MainScreen");
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "GameScreen");
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void ButtonOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOptionActionPerformed
        JPOpciones.cardAnterior="MainScreen";
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "OptionScreen");
    }//GEN-LAST:event_ButtonOptionActionPerformed

    private void ButtonCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreditsActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "CreditsScreen");
    }//GEN-LAST:event_ButtonCreditsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCredits;
    private javax.swing.JButton ButtonOption;
    private javax.swing.JButton ButtonStart;
    // End of variables declaration//GEN-END:variables
}
