/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class JPInfoPartidas extends javax.swing.JPanel {

    private Image imgFondo;
    private List<Partida> partidas;
    DefaultTableModel modelo = new DefaultTableModel();
    
    public JPInfoPartidas() {
        try{
            imgFondo = ImageIO.read(new File("src/Resources/Fondos/Fondo6.png"));
        }catch(Exception e){
            System.out.println("*** Error cargando fondo de panel ***");
            e.printStackTrace();
        }
        
        initComponents();
        modelo.addColumn("Jugador 1");
        modelo.addColumn("Jugador 2");
        modelo.addColumn("Ganador");
        modelo.addColumn("Personaje");
        modelo.addColumn("Fecha");
        modelo.addColumn("Duracion");
        this.jTableDatos.setModel(modelo);
        this.ButtonReturn.setIcon(ButtonIcons.getBackButtonNormal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButtonNombre = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelDuracion = new javax.swing.JLabel();
        jButtonDuracion = new javax.swing.JButton();
        ButtonReturn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jTableDatos.setBackground(new java.awt.Color(255, 245, 202));
        jTableDatos.setFont(StardewFonts.getSVThin());
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDatos);

        jButtonNombre.setBackground(new java.awt.Color(218, 173, 114));
        jButtonNombre.setFont(StardewFonts.getSVBold());
        jButtonNombre.setText("Mostrar Datos");
        jButtonNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(177, 78, 5)));
        jButtonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombreActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(StardewFonts.getSVSmallTitle());
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Informacion de Partidas");

        jLabelNombre.setBackground(new java.awt.Color(218, 173, 114));
        jLabelNombre.setFont(StardewFonts.getSVBold());
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Busqueda por Nombre:");
        jLabelNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(177, 78, 5)));
        jLabelNombre.setOpaque(true);

        jTextFieldNombre.setFont(StardewFonts.getSVThin());

        jLabelDuracion.setBackground(new java.awt.Color(218, 173, 114));
        jLabelDuracion.setFont(StardewFonts.getSVBold());
        jLabelDuracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDuracion.setText("Mostrar todo por duracion:");
        jLabelDuracion.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(177, 78, 5)));
        jLabelDuracion.setOpaque(true);

        jButtonDuracion.setBackground(new java.awt.Color(218, 173, 114));
        jButtonDuracion.setFont(StardewFonts.getSVBold());
        jButtonDuracion.setText("Mostrar Datos");
        jButtonDuracion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(177, 78, 5)));
        jButtonDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDuracionActionPerformed(evt);
            }
        });

        ButtonReturn.setBackground(new Color(0,0,0,0));
        ButtonReturn.setFont(StardewFonts.getSVBold());
        ButtonReturn.setBorder(null);
        ButtonReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonReturn.setMaximumSize(new java.awt.Dimension(132, 54));
        ButtonReturn.setMinimumSize(new java.awt.Dimension(132, 54));
        ButtonReturn.setPreferredSize(new java.awt.Dimension(132, 54));
        ButtonReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonReturnMouseExited(evt);
            }
        });
        ButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelNombre)
                .addGap(237, 237, 237)
                .addComponent(jLabelDuracion)
                .addGap(333, 333, 333))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248)
                                .addComponent(jButtonDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLabelTitulo.setBorder(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombreActionPerformed
        String nombre = this.jLabelNombre.getText().trim();
        this.partidas = ConexionBD.obtenerPartidas();
        int i=0;
        String datos[] = new String[6];
            if (partidas.isEmpty()){
                JOptionPane.showMessageDialog(this, "Partidas no encontradas");
            }
            else{
                String datoabuscar = this.jTextFieldNombre.getText().trim(); 
                if (modelo.getRowCount() !=0) //si hay datos en pantalla de la consulta anterior
                { 
                    modelo.setRowCount(0);
                    this.jTableDatos.repaint(); //repinta la tabla
                }
                for (i=0; i<partidas.size(); i++)
                {
                    if (datoabuscar.equals(partidas.get(i).getJugador1()) || datoabuscar.equals(partidas.get(i).getJugador2())) {
                        datos[0]=partidas.get(i).getJugador1();
                        datos[1]=partidas.get(i).getJugador2();
                        datos[2]=partidas.get(i).getGanador();
                        datos[3]=partidas.get(i).getPersonaje();
                        datos[4]=partidas.get(i).getFecha();
                        datos[5]=partidas.get(i).getTiempo();
                            //se agregan los datos a la tabla
                        modelo.addRow(datos);
                    }
                }//fin for
                if (modelo.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "El nombre no esta en la lista");
            }
    }//GEN-LAST:event_jButtonNombreActionPerformed

    private void jButtonDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDuracionActionPerformed
        this.partidas = ConexionBD.obtenerPartidas();
        int i=0;
        String datos[] = new String[6];
            if (partidas.isEmpty()){
                JOptionPane.showMessageDialog(this, "Partidas no encontradas");
            }
            else{
                if (modelo.getRowCount() !=0) //si hay datos en pantalla de la consulta anterior
                { 
                    modelo.setRowCount(0);
                    this.jTableDatos.repaint(); //repinta la tabla
                }
                for (i=0; i<partidas.size(); i++)
                {
                    datos[0]=partidas.get(i).getJugador1();
                    datos[1]=partidas.get(i).getJugador2();
                    datos[2]=partidas.get(i).getGanador();
                    datos[3]=partidas.get(i).getPersonaje();
                    datos[4]=partidas.get(i).getFecha();
                    datos[5]=partidas.get(i).getTiempo();
                        //se agregan los datos a la tabla
                    modelo.addRow(datos);
                }//fin for
            }
    }//GEN-LAST:event_jButtonDuracionActionPerformed

    private void ButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReturnActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "MainScreen");
    }//GEN-LAST:event_ButtonReturnActionPerformed

    private void ButtonReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonReturnMouseEntered
        this.ButtonReturn.setIcon(ButtonIcons.getBackButtonHover());
    }//GEN-LAST:event_ButtonReturnMouseEntered

    private void ButtonReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonReturnMouseExited
        this.ButtonReturn.setIcon(ButtonIcons.getBackButtonNormal());
    }//GEN-LAST:event_ButtonReturnMouseExited

    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(imgFondo != null){
            g.drawImage(imgFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReturn;
    private javax.swing.JButton jButtonDuracion;
    private javax.swing.JButton jButtonNombre;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
