/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.*;
import javax.swing.*;

// @author LENOVO

public class JPInicio extends javax.swing.JPanel {
    
    // Creates new form JPInicio
    public JPInicio() {
        this.setFont(StardewFonts.getSVThin());
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonStart = new javax.swing.JButton();
        ButtonInstrucc = new javax.swing.JButton();
        ButtonCredits = new javax.swing.JButton();
        ButtonOptions = new javax.swing.JButton();

        setFont(getFont());
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        ButtonStart.setFont(StardewFonts.getSVBold());
        ButtonStart.setBorder(null);
        ButtonStart.setBorderPainted(false);
        ButtonStart.setLabel("Jugar");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        ButtonInstrucc.setFont(getFont());
        ButtonInstrucc.setText("Instrucciones");
        ButtonInstrucc.setBorder(null);
        ButtonInstrucc.setBorderPainted(false);
        ButtonInstrucc.setIconTextGap(0);
        ButtonInstrucc.setInheritsPopupMenu(true);
        ButtonInstrucc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInstruccActionPerformed(evt);
            }
        });

        ButtonCredits.setFont(getFont());
        ButtonCredits.setText("Creditos");
        ButtonCredits.setBorder(null);
        ButtonCredits.setBorderPainted(false);
        ButtonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreditsActionPerformed(evt);
            }
        });

        ButtonOptions.setFont(getFont());
        ButtonOptions.setText("Opciones");
        ButtonOptions.setBorder(null);
        ButtonOptions.setBorderPainted(false);
        ButtonOptions.setIconTextGap(0);
        ButtonOptions.setInheritsPopupMenu(true);
        ButtonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(490, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonInstrucc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonInstrucc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        ButtonInstrucc.getAccessibleContext().setAccessibleName("InstruccionesButton");
        ButtonOptions.getAccessibleContext().setAccessibleName("OpcionesButton");

        getAccessibleContext().setAccessibleName("MainScreen");
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "SetUpScreen");
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void ButtonInstruccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInstruccActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "InstructScreen");
    }//GEN-LAST:event_ButtonInstruccActionPerformed

    private void ButtonCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreditsActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "CreditsScreen");
    }//GEN-LAST:event_ButtonCreditsActionPerformed

    private void ButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOptionsActionPerformed
        JPOpciones.cardAnterior="MainScreen";
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "OptionScreen");
    }//GEN-LAST:event_ButtonOptionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCredits;
    private javax.swing.JButton ButtonInstrucc;
    private javax.swing.JButton ButtonOptions;
    private javax.swing.JButton ButtonStart;
    // End of variables declaration//GEN-END:variables
}
