/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

public class JPSetUp extends javax.swing.JPanel {

    private Image imgFondo;
    /**
     * Creates new form JPSetUp
     */
    public JPSetUp() {
        this.setFont(StardewFonts.getSVThin());
        try{
            imgFondo = ImageIO.read(new File("src/Resources/Fondos/Fondo11.png"));
        }catch(Exception e){
            System.out.println("*** Error cargando fondo de panel ***");
            e.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupModoSeleccion = new javax.swing.ButtonGroup();
        jButtonStartGame = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        jToggleButtonElegirLista = new javax.swing.JToggleButton();
        jToggleButtonElegirTabla = new javax.swing.JToggleButton();
        jToggleButtonElegirAzar = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jButtonStartGame.setText("Start");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Ingrese su nombre de jugador:");

        jLabelModo.setText("Seleccione el modo de seleccion de personaje:");

        buttonGroupModoSeleccion.add(jToggleButtonElegirLista);
        jToggleButtonElegirLista.setText("Seleccion de Lista");

        buttonGroupModoSeleccion.add(jToggleButtonElegirTabla);
        jToggleButtonElegirTabla.setText("Seleccion de Tabla");

        buttonGroupModoSeleccion.add(jToggleButtonElegirAzar);
        jToggleButtonElegirAzar.setText("Aleatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModo)
                            .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonElegirLista)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonElegirTabla)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonElegirAzar)))))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jLabelModo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonElegirLista)
                    .addComponent(jToggleButtonElegirTabla)
                    .addComponent(jToggleButtonElegirAzar))
                .addGap(117, 117, 117)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "GameScreen");
    }//GEN-LAST:event_jButtonStartGameActionPerformed
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(imgFondo != null){
            g.drawImage(imgFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModoSeleccion;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JToggleButton jToggleButtonElegirAzar;
    private javax.swing.JToggleButton jToggleButtonElegirLista;
    private javax.swing.JToggleButton jToggleButtonElegirTabla;
    // End of variables declaration//GEN-END:variables
}
