/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

public class JPSetUp extends javax.swing.JPanel {
    // Variables
    private Image imgFondo;
    private Client jugador;
    private ArrayList personajes;
    
    // Creates new form JPSetUp
    public JPSetUp(Client jugador) {
        this.setFont(StardewFonts.getSVThin());
        this.jugador = jugador;
        
        try{
            imgFondo = ImageIO.read(new File("src/Resources/Fondos/Fondo11.png"));
        }catch(Exception e){
            System.out.println("*** Error cargando fondo de panel ***");
            e.printStackTrace();
        }
        
        initComponents();
    }

    protected void obtenerPersonajes(ArrayList tablero){
        this.personajes = tablero;
    }
    
    protected void moverAJuego(){
        JPJuego.setNombre(this.jTextFieldNombreJ.getText());
        JPanel parent = (JPanel)getParent();
        CardLayout cardLayout = (CardLayout)parent.getLayout();
        cardLayout.show(parent, "GameScreen");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupModoSeleccion = new javax.swing.ButtonGroup();
        jButtonStartGame = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        jToggleButtonElegirLista = new javax.swing.JToggleButton();
        jToggleButtonElegirTabla = new javax.swing.JToggleButton();
        jToggleButtonElegirAzar = new javax.swing.JToggleButton();
        jTextFieldNombreJ = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jButtonStartGame.setFont(StardewFonts.getSVBold());
        jButtonStartGame.setText("Start");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(StardewFonts.getSVBold());
        jLabelNombre.setText("Ingrese su nombre de jugador:");

        jLabelModo.setFont(StardewFonts.getSVBold());
        jLabelModo.setText("Seleccione el modo de seleccion de personaje:");

        buttonGroupModoSeleccion.add(jToggleButtonElegirLista);
        jToggleButtonElegirLista.setFont(StardewFonts.getSVBold());
        jToggleButtonElegirLista.setText("Seleccion de Lista");

        buttonGroupModoSeleccion.add(jToggleButtonElegirTabla);
        jToggleButtonElegirTabla.setFont(StardewFonts.getSVBold());
        jToggleButtonElegirTabla.setText("Seleccion de Tabla");

        buttonGroupModoSeleccion.add(jToggleButtonElegirAzar);
        jToggleButtonElegirAzar.setFont(StardewFonts.getSVBold());
        jToggleButtonElegirAzar.setText("Aleatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonElegirLista)
                                .addGap(20, 20, 20)
                                .addComponent(jToggleButtonElegirTabla))
                            .addComponent(jLabelModo)
                            .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addComponent(jToggleButtonElegirAzar)))
                .addGap(515, 515, 515))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabelNombre)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabelModo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonElegirLista)
                    .addComponent(jToggleButtonElegirTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonElegirAzar)
                .addGap(44, 44, 44)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        jTextFieldNombreJ.setOpaque(false);
        jTextFieldNombreJ.setBackground(new java.awt.Color(0,0,0,0));
        jTextFieldNombreJ.setBorder(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        // this.jugador.enviarPreparado();
        this.jugador.enviarPregunta("Texto de prueba");
    }//GEN-LAST:event_jButtonStartGameActionPerformed
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(imgFondo != null){
            g.drawImage(imgFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModoSeleccion;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldNombreJ;
    private javax.swing.JToggleButton jToggleButtonElegirAzar;
    private javax.swing.JToggleButton jToggleButtonElegirLista;
    private javax.swing.JToggleButton jToggleButtonElegirTabla;
    // End of variables declaration//GEN-END:variables
}
