/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misClases;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Elijah
 */
public class JPVictoria extends javax.swing.JPanel {
    // Variables
    private JFrame contenedorPrincipal; // Ventana que contiene los paneles
    
    /**
     * Creates new form JPVictoria
     */
    public JPVictoria() {
        this.setFont(StardewFonts.getSVThin());
         this.contenedorPrincipal = contenedorPrincipal;
        this.setFont(StardewFonts.getSVThin());
        initComponents();
        configurarEventos();
    }
    
    private void configurarEventos() {
        jButtonRegInicio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Buscar el panel contenedor y cambiar al panel "inicio"
                Container parent = contenedorPrincipal.getContentPane();
                if (parent.getLayout() instanceof CardLayout) {
                    CardLayout cl = (CardLayout) parent.getLayout();
                    cl.show(parent, "MainScreen");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegInicio = new javax.swing.JButton();

        setFont(getFont());
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jButtonRegInicio.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButtonRegInicio)
                .addContainerGap(906, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jButtonRegInicio)
                .addContainerGap(365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegInicio;
    // End of variables declaration//GEN-END:variables
}
